### ISSUE TITLE
Move to designa?

### ISSUE THREAD

**Issue by nokome** [stencila/email-templates#3]
Thanks for setting this up @alex-ketch. To avoid YAR (Yet Another Repo) and given that brand assets are already in `designa`, I feel like a more natural place for this would be as a package there. Any potential problems with that?

**Comment by alex-ketch** [comment]
I’m inclined to keep it separate for a few minor reasons, but not dead set against moving to designa if you feel strongly in favor of doing so.
I understood this project being closer to `thema`, in that it is close to the final usage, whereas `designa` provides a bit more low-level building blocks for use in other projects.
Some of the other reasons are that:
- there isn’t a very good way of consuming styles/assets from designa through MJML, so there doesn’t exist any real dependency on designa packages
- I imagine these templates will likely change at a much slower cadence than the designa packages
- it will add more build overhead and space usage for people working in designa, as well as CI iteration times
- I’m not sure if it makes sense to publish this as a package. I don’t know if we can easily tell Lerna to avoid publishing a certain package while still being able to target build commands at the package, but can take a look if you’d like. (Setting `private: true` will cause a complete build failure I think)

**Comment by nokome** [comment]
Fair enough, let's leave it as is.
