### ISSUE TITLE
Newsletter Signup Confirmation message

### ISSUE THREAD

**Issue by alex-ketch** [stencila/email-templates#5]
> Below is the current draft of the email content, please update this message, or comment below with any suggested changes.

---

# Thank you for your interest!

We’re busy working on our beta tester programme and will let you know as soon
as we’re ready.

Meanwhile, we’ll send you our newsletter as well as invitations to our monthly
community calls where you can join us to see what’s new, provide feedback,
give us ideas, and ask any questions.

Best regards,
Team Stencila
💖

**Comment by nokome** [comment]
Thanks! A few edits made but looks good.
